/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/_index'
import { Route as OgRouteImport } from './routes/og'
import { Route as IndexIndexRouteImport } from './routes/_index/index'
import { Route as IndexEducationRouteImport } from './routes/_index/education'
import { Route as IndexProjectsRouteImport } from './routes/_index/projects'
import { Route as IndexWorkRouteImport } from './routes/_index/work'

const IndexRoute = IndexRouteImport.update({
  id: '/_index',
  getParentRoute: () => rootRouteImport,
} as any)
const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexIndexRoute = IndexIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndexRoute,
} as any)
const IndexEducationRoute = IndexEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => IndexRoute,
} as any)
const IndexProjectsRoute = IndexProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => IndexRoute,
} as any)
const IndexWorkRoute = IndexWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => IndexRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexIndexRoute
  '/og': typeof OgRoute
  '/education': typeof IndexEducationRoute
  '/projects': typeof IndexProjectsRoute
  '/work': typeof IndexWorkRoute
}
export interface FileRoutesByTo {
  '/og': typeof OgRoute
  '/education': typeof IndexEducationRoute
  '/projects': typeof IndexProjectsRoute
  '/work': typeof IndexWorkRoute
  '/': typeof IndexIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_index': typeof IndexRouteWithChildren
  '/og': typeof OgRoute
  '/_index/education': typeof IndexEducationRoute
  '/_index/projects': typeof IndexProjectsRoute
  '/_index/work': typeof IndexWorkRoute
  '/_index/': typeof IndexIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/og' | '/education' | '/projects' | '/work'
  fileRoutesByTo: FileRoutesByTo
  to: '/og' | '/education' | '/projects' | '/work' | '/'
  id:
    | '__root__'
    | '/_index'
    | '/og'
    | '/_index/education'
    | '/_index/projects'
    | '/_index/work'
    | '/_index/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRouteWithChildren
  OgRoute: typeof OgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_index': {
      id: '/_index'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_index/': {
      id: '/_index/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexIndexRouteImport
      parentRoute: typeof IndexRoute
    }
    '/_index/education': {
      id: '/_index/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof IndexEducationRouteImport
      parentRoute: typeof IndexRoute
    }
    '/_index/projects': {
      id: '/_index/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof IndexProjectsRouteImport
      parentRoute: typeof IndexRoute
    }
    '/_index/work': {
      id: '/_index/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof IndexWorkRouteImport
      parentRoute: typeof IndexRoute
    }
  }
}

interface IndexRouteChildren {
  IndexEducationRoute: typeof IndexEducationRoute
  IndexProjectsRoute: typeof IndexProjectsRoute
  IndexWorkRoute: typeof IndexWorkRoute
  IndexIndexRoute: typeof IndexIndexRoute
}

const IndexRouteChildren: IndexRouteChildren = {
  IndexEducationRoute: IndexEducationRoute,
  IndexProjectsRoute: IndexProjectsRoute,
  IndexWorkRoute: IndexWorkRoute,
  IndexIndexRoute: IndexIndexRoute,
}

const IndexRouteWithChildren = IndexRoute._addFileChildren(IndexRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRouteWithChildren,
  OgRoute: OgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
